package baekjoon;

import baekjoon.config.ProblemTestConfigure;
import java.io.IOException;
import java.util.stream.Stream;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

class Problem_27495_Test extends ProblemTestConfigure {

    @ParameterizedTest
    @MethodSource("testCase")
    protected void test(String input, String actual) throws IOException {
        run(input, actual, new Problem_27495());
    }

    private static Stream<Arguments> testCase() {
        return Stream.of(
            Arguments.of(
                "s11 s12 s13 s21 s22 s23 s31 s32 s33\n"
                    + "s18 m1 s14 s28 m2 s24 s38 m3 s34\n"
                    + "s17 s16 s15 s27 s26 s25 s37 s36 s35\n"
                    + "s81 s82 s83 m1 m2 m3 s41 s42 s43\n"
                    + "s88 m8 s84 m8 f m4 s48 m4 s44\n"
                    + "s87 s86 s85 m7 m6 m5 s47 s46 s45\n"
                    + "s71 s72 s73 s61 s62 s63 s51 s52 s53\n"
                    + "s78 m7 s74 s68 m6 s64 s58 m5 s54\n"
                    + "s77 s76 s75 s67 s66 s65 s57 s56 s55",
                "#1. m1\n"
                    + "#1-1. s11\n"
                    + "#1-2. s12\n"
                    + "#1-3. s13\n"
                    + "#1-4. s14\n"
                    + "#1-5. s15\n"
                    + "#1-6. s16\n"
                    + "#1-7. s17\n"
                    + "#1-8. s18\n"
                    + "#2. m2\n"
                    + "#2-1. s21\n"
                    + "#2-2. s22\n"
                    + "#2-3. s23\n"
                    + "#2-4. s24\n"
                    + "#2-5. s25\n"
                    + "#2-6. s26\n"
                    + "#2-7. s27\n"
                    + "#2-8. s28\n"
                    + "#3. m3\n"
                    + "#3-1. s31\n"
                    + "#3-2. s32\n"
                    + "#3-3. s33\n"
                    + "#3-4. s34\n"
                    + "#3-5. s35\n"
                    + "#3-6. s36\n"
                    + "#3-7. s37\n"
                    + "#3-8. s38\n"
                    + "#4. m4\n"
                    + "#4-1. s41\n"
                    + "#4-2. s42\n"
                    + "#4-3. s43\n"
                    + "#4-4. s44\n"
                    + "#4-5. s45\n"
                    + "#4-6. s46\n"
                    + "#4-7. s47\n"
                    + "#4-8. s48\n"
                    + "#5. m5\n"
                    + "#5-1. s51\n"
                    + "#5-2. s52\n"
                    + "#5-3. s53\n"
                    + "#5-4. s54\n"
                    + "#5-5. s55\n"
                    + "#5-6. s56\n"
                    + "#5-7. s57\n"
                    + "#5-8. s58\n"
                    + "#6. m6\n"
                    + "#6-1. s61\n"
                    + "#6-2. s62\n"
                    + "#6-3. s63\n"
                    + "#6-4. s64\n"
                    + "#6-5. s65\n"
                    + "#6-6. s66\n"
                    + "#6-7. s67\n"
                    + "#6-8. s68\n"
                    + "#7. m7\n"
                    + "#7-1. s71\n"
                    + "#7-2. s72\n"
                    + "#7-3. s73\n"
                    + "#7-4. s74\n"
                    + "#7-5. s75\n"
                    + "#7-6. s76\n"
                    + "#7-7. s77\n"
                    + "#7-8. s78\n"
                    + "#8. m8\n"
                    + "#8-1. s81\n"
                    + "#8-2. s82\n"
                    + "#8-3. s83\n"
                    + "#8-4. s84\n"
                    + "#8-5. s85\n"
                    + "#8-6. s86\n"
                    + "#8-7. s87\n"
                    + "#8-8. s88"
            ),
            Arguments.of(
                "CareTheBody TakeSupplements FSQ90kg ImproveInStep StrengthenTheBodyCore1 StabilizeThePivot CreateAnAngle HitTheBallFromAbove StrengthenTheWrist\n"
                    + "Flexibility Physical RSQ130kg StabilizeTheReleasePoint Control GetRidOfUneasyFeelings DoNotTenseUp Precision TheLowerBodyLeads\n"
                    + "Stamina RangeOfMotion1 Meals StrengthenTheLowerExtremities1 DontOpenTheBody ControlMental ReleaseTheBallInTheFront IncreaseTheNumberOfRotations RangeOfMotion2\n"
                    + "HaveDearGoalsAndPurposes DoNotSwingJoyAndSorrow CoolHeadAndHotPassion Physical Control Precision TurnAtThePivot StrengthenTheLowerExtremities2 GainWeight\n"
                    + "BeStrongAtPinches Mental DontSwayByAtmosphere Mental DraftNo1 Speed160kmhr StrengthenTheBodyCore2 Speed160kmhr StrengthenAroundTheShoulders\n"
                    + "DontCreateUpsAndDowns TenacityForVictory TheHeartToCareTeamMates Personality Luck CurveBalls RangeOfMotion3 CatchLinerBalls IncreasePitching\n"
                    + "Sensitivity WorthyToBeLoved PlanAhead Greetings PickingTrashes CleanTheRoom IncreaseCoundBalls PrecisionForkBalls PrecisionOfSliders\n"
                    + "Caring Personality Gratitude UseTheToolsWithCare Luck AttitudeForJudges CurveBallsWithSpeed CurveBalls DecisiveBallsForLeftBatter\n"
                    + "WellMannered WorthyToBeTrusted SustainedEfforts PositiveThinking WorthyToBeSupported ReadBooks PitchWithTheSameAsStraight ControlFromStrikeIntoBall ImagineTheDepth",
                "#1. Control\n"
                    + "#1-1. ControlMental\n"
                    + "#1-2. DontOpenTheBody\n"
                    + "#1-3. GetRidOfUneasyFeelings\n"
                    + "#1-4. ImproveInStep\n"
                    + "#1-5. StabilizeThePivot\n"
                    + "#1-6. StabilizeTheReleasePoint\n"
                    + "#1-7. StrengthenTheBodyCore1\n"
                    + "#1-8. StrengthenTheLowerExtremities1\n"
                    + "#2. CurveBalls\n"
                    + "#2-1. ControlFromStrikeIntoBall\n"
                    + "#2-2. CurveBallsWithSpeed\n"
                    + "#2-3. DecisiveBallsForLeftBatter\n"
                    + "#2-4. ImagineTheDepth\n"
                    + "#2-5. IncreaseCoundBalls\n"
                    + "#2-6. PitchWithTheSameAsStraight\n"
                    + "#2-7. PrecisionForkBalls\n"
                    + "#2-8. PrecisionOfSliders\n"
                    + "#3. Luck\n"
                    + "#3-1. AttitudeForJudges\n"
                    + "#3-2. CleanTheRoom\n"
                    + "#3-3. Greetings\n"
                    + "#3-4. PickingTrashes\n"
                    + "#3-5. PositiveThinking\n"
                    + "#3-6. ReadBooks\n"
                    + "#3-7. UseTheToolsWithCare\n"
                    + "#3-8. WorthyToBeSupported\n"
                    + "#4. Mental\n"
                    + "#4-1. BeStrongAtPinches\n"
                    + "#4-2. CoolHeadAndHotPassion\n"
                    + "#4-3. DoNotSwingJoyAndSorrow\n"
                    + "#4-4. DontCreateUpsAndDowns\n"
                    + "#4-5. DontSwayByAtmosphere\n"
                    + "#4-6. HaveDearGoalsAndPurposes\n"
                    + "#4-7. TenacityForVictory\n"
                    + "#4-8. TheHeartToCareTeamMates\n"
                    + "#5. Personality\n"
                    + "#5-1. Caring\n"
                    + "#5-2. Gratitude\n"
                    + "#5-3. PlanAhead\n"
                    + "#5-4. Sensitivity\n"
                    + "#5-5. SustainedEfforts\n"
                    + "#5-6. WellMannered\n"
                    + "#5-7. WorthyToBeLoved\n"
                    + "#5-8. WorthyToBeTrusted\n"
                    + "#6. Physical\n"
                    + "#6-1. CareTheBody\n"
                    + "#6-2. FSQ90kg\n"
                    + "#6-3. Flexibility\n"
                    + "#6-4. Meals\n"
                    + "#6-5. RSQ130kg\n"
                    + "#6-6. RangeOfMotion1\n"
                    + "#6-7. Stamina\n"
                    + "#6-8. TakeSupplements\n"
                    + "#7. Precision\n"
                    + "#7-1. CreateAnAngle\n"
                    + "#7-2. DoNotTenseUp\n"
                    + "#7-3. HitTheBallFromAbove\n"
                    + "#7-4. IncreaseTheNumberOfRotations\n"
                    + "#7-5. RangeOfMotion2\n"
                    + "#7-6. ReleaseTheBallInTheFront\n"
                    + "#7-7. StrengthenTheWrist\n"
                    + "#7-8. TheLowerBodyLeads\n"
                    + "#8. Speed160kmhr\n"
                    + "#8-1. CatchLinerBalls\n"
                    + "#8-2. GainWeight\n"
                    + "#8-3. IncreasePitching\n"
                    + "#8-4. RangeOfMotion3\n"
                    + "#8-5. StrengthenAroundTheShoulders\n"
                    + "#8-6. StrengthenTheBodyCore2\n"
                    + "#8-7. StrengthenTheLowerExtremities2\n"
                    + "#8-8. TurnAtThePivot"
            )
        );
    }
}